<center><img src="https://raw.githubusercontent.com/jotaraul/cv_hub/refs/heads/main/appendices/images/jupyter_logo.png" width="500"></center>

# Appendix 1. Introduction to Jupyter and Python


During this course, we are going to use this software called *Jupyter notebook*, which allows us to write and execute Python code at the moment.

Jupyter notebooks are divided in **cells** that can be executed by pressing <kbd>Ctrl</kbd> + <kbd>Enter</kbd>. There are two main types of cells, **Markdown cells** and **Python cells**. Markdown cells are used for writting text
and Python cells for writting code that can be executed.

In [4]:
# This is a Python cell!!

# This cell can be executed pressing ctrl + enter on it

print(10*10)

100


## Used libraries

There are two Python libraries that we are going to use frequently in our sessions:

<center><img src="https://raw.githubusercontent.com/jotaraul/cv_hub/refs/heads/main/appendices/images/numpy_logo.png" width="300" align="left"/><img src="https://raw.githubusercontent.com/jotaraul/cv_hub/refs/heads/main/appendices/images/opencv_logo.png" width="300" align="rigth"/></center>



- **NumPy** add support for multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
- **OpenCV** is a library of programming functions mainly aimed at real-time computer vision and image processing.

## NumPy introduction

For those who are not familiar with Python and NumPy, a tutorial for getting started has been prepared. Here, we are going to understand the basics of Numpy arrays and Python programming.

In [5]:
import numpy # Import library

Arrays are created using `numpy.array`

In [6]:
identity = numpy.array([[1,0,0],[0,1,0],[0,0,1]])
print("Identity matrix: \n", identity)

Identity matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


NumPy arrays have a shape attribute that returns a tuple containing the length of each dimension of the array.

*A tuple is a sequence of immutable Python objects. Tuples are sequences, just like lists. The differences between tuples and lists are, the tuples cannot be changed unlike lists and tuples use parentheses, whereas lists use square brackets.*

In [7]:
print("Identity matrix shape:", identity.shape)

Identity matrix shape: (3, 3)


There are some helpful methods for array creation, see [array creation routines](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html). We will see the most common ones.

In [8]:
zeros = numpy.zeros((2,3)) # (2,3) is a tuple containing the shape of the matrix, parenthesis are required
print("Zeros:\n", zeros)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ones = numpy.ones((3,2))
print("Ones: \n", ones)

Ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
constant = numpy.full((3,3),7)
print("Constant:\n", constant)
# There are many more ...

Constant:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


We can rename modules using `import as`

In [11]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Arrays in Python are 0-indexed, you can access single elements using square brackets notation.

In [12]:
first_row = a[0]
print("First_row:\n", first_row)

First_row:
 [1 2 3 4]


It is possible to use negative indexing, accessing the array backwards

In [13]:
last_row = a[-1] # This is equivalent to a[a.shape[0]-1]
print("Last_row: \n", last_row)

Last_row: 
 [ 9 10 11 12]


In [14]:
element = a[2,2] # Third element of third column
print("Element: \n", element)

Element: 
 11


**Slicing** allows taking more than one element in one step. Slice object uses `start:stop:step` notation, we can skip `start` and `stop` if they are array limits, and `step` if is 1.

In [15]:
last_column = a[:,-1]
print("Last column:\n", last_column)

Last column:
 [ 4  8 12]


In [16]:
last_two_columns = a[:,-2:]
print("Last two columns: \n", last_two_columns)

Last two columns: 
 [[ 3  4]
 [ 7  8]
 [11 12]]


We can easily take subarrays using slices

In [17]:
cropped_a = a[1:3,-2:]
print("Cropped: \n",cropped_a)

Cropped: 
 [[ 7  8]
 [11 12]]


You can learn more about Numpy indexing on [numpy documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

## OpenCV introduction

Now, we are going to learn OpenCV basics, such as reading, saving and displaying images.

*Note that when we read an image using OpenCV methods, it is read as a NumPy array.*

In [18]:
import cv2 # Import OpenCV
import numpy as np

Matplotlib is useful for image displaying

In [19]:
import matplotlib
from matplotlib import pyplot as plt # Import matplotlib.pyplot module
matplotlib.rcParams['figure.figsize'] = (6.0, 6.0) # Set default figure size

In [20]:
# Read gray image

images_path = './images/'
image = cv2.imread(images_path + 'hotel.jpg',0) # 0 read any image as gray
print(image)

None


Gray images have 1 band (2D-arrays)

In [21]:
print(image.shape)

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
#Display image

plt.imshow(image, cmap='gray')
plt.title('Example gray image')
plt.show()

In [ ]:
# Read RGB image

image = cv2.imread(images_path + 'hotel.jpg',-1) # -1 read any image as BGR
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # OpenCV reads images as BGR, but we need them in RGB
print(image)

RGB images have 3 bands (3D-arrays)

In [ ]:
print(image.shape)

In [ ]:
#Display RGB image
plt.imshow(image)
plt.title('Example RGB image')
plt.show()

Images can be cropped taking the piece of the array we are interested in

In [ ]:
cropped_image = image[430:660,340:510]
print(cropped_image.shape)

In [ ]:
plt.imshow(cropped_image)
plt.show()

Also we can modify them

In [ ]:
img_goku = cv2.imread(images_path + 'goku_cloud.png',-1) # -1 read any image as BGR
img_goku = cv2.cvtColor(img_goku, cv2.COLOR_BGR2RGB) # OpenCV reads images as BGR, but we need them in RGB
img_goku_resized = cv2.resize(img_goku, (130,140))

image[100:240,580:710] = img_goku_resized[:,:,:3]

plt.imshow(image)
plt.show()